### ISSUE TITLE
Cannot archive using latest release 1.0.2.19 (Undefined symbols for architecture armv7)

### ISSUE THREAD

**Issue by MikeSpelling** [levigroker/GRKOpenSSLFramework#10]
Although my code seems to compile and run fine, when I attempt to archive on either XCode 10 or XCode 11 I receive a number of errors in the console regarding the armv7 architecture. This problem does not seem to be present in 1.0.2.18.

Undefined symbols for architecture armv7:
_BIO_s_mem_SHA1_Init_SHA1_Final_d2i_PKCS7_bio_OpenSSL_add_all_digests_ASN1_INTEGER_get_ASN1_INTEGER_free_SHA1_Update_BIO_new_BIO_write_ASN1_get_object_d2i_X509_bio_c2i_ASN1_INTEGER
_PKCS7_verify
_X509_STORE_new
_OBJ_obj2nid
_X509_STORE_add_cert
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mrcararia** [comment]
Same here.  👍🏼

**Comment by levigroker** [comment]
Any more information or an example project or anything might be useful. Thanks.

**Comment by MikeSpelling** [comment]
I'm doing local receipt validation using: https://github.com/andrewcbancroft/SwiftyLocalReceiptValidator in combination with OpenSSL from this pod. I don't have an example project to easily share I'm afraid but if theres any more information you need I can try to provide it?

**Comment by MikeSpelling** [comment]
May be worth mentioning that on 1.0.2.18 I can create an archive fine and export it for app store. However, trying to export for ad-hoc gives the following error:

Failed to verify bitcode in openssl.framework/openssl:
error: Linker option verification failed for bundle /var/folders/.../openssl.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

This isn't present in 1.0.2.16

**Comment by levigroker** [comment]
If you still have Xcode 10.x I'd encourage you to try to build the project yourself and see if it's a build system issue. The instructions are (I think) pretty clear.

**Comment by thejeff77** [comment]
1.0.2 is deprecated, and shouldn't be used. Also its good to avoid downloading pre-compiled stuff. Figured I'd post this since I just went through all of the iOS OpenSSL pain myself.

Here are two options I recommend:

I forked an older pod and updated it for 1.1.1d (latest OpenSSL release), and it works great for all architectures back to iOS 8 and integrates with swift/bitcode-enabled projects up to XCode 11.3 (latest as of today)

Add to podfile:

`pod 'OpenSSL', :git => 'https://github.com/thejeff77/OpenSSL-Pod.git'`

Another project I'd recommend is just a script that builds a drop-in OpenSSL framework, which is also awesome, and a little less intrusive than Pods if you don't have CocoaPods integrated yet:

https://github.com/keeshux/openssl-apple

Cheers.

**Comment by levicoradine** [comment]
@thejeff77 I'm trying to think of how not to take offense to your comments to prefer your "Unmaintained - please fork" pod over mine.

* This pod is not trying to be on the latest version. Many legacy systems are unable to spend the time to migrate from 1.0.x to 1.1.x, and therefore this is relevant.
* "good to avoid downloading pre-compiled stuff" is a reasonable statement, especially when it comes to security software, *but* I have spent considerable effort to on documenting how to download, build, and validate this pod from source yourself, *and* take the security of the builds very seriously, validating them personally.
* Lastly, I'm all for learning about alternatives which may work better for different workflows, and use cases, but this is hardly the place to post about that. It's akin to someone putting a bumpersticker on your car for a car wash service.

**Comment by thejeff77** [comment]
@levicoradine didn't mean to trigger your offense. Its not personal, I don't know you.

I forked it and maintained it (upgraded). Haven't gotten around to updating the title copied from the original source.

**Comment by levigroker** [comment]
Closing as I'm no longer supporting 1.0.2. Please consider using 1.1.1:

 🚀  GRKOpenSSLFramework (1.1.1.11) successfully published
 📅  September 17th, 19:12
 🌎  https://cocoapods.org/pods/GRKOpenSSLFramework
